### ISSUE TITLE
Choppy videos in Firefox 

### ISSUE THREAD

**Issue by Rob75018** [picssel/mp4-videos-mediaelement-fancybox#1]
When loaded using the flash fallback in firefox, videos skip frames... Naturally doesn't have this problem on webkit browsers, but the flash fallback still works great on firefox when used without fancybox.

Leaves me perplexed.

**Comment by picssel** [comment]
@Rob75018 what are the settings/code you are using? can you create a jsfiddle to reproduce the issue? does the demo http://www.picssel.com/demos/play_videos_with_mediaelement_in_fancybox.html work for you (in Firefox)? ... what version of Firefox? Works fine for me in Firefox (Windows) v30+ (currently using v33)

**EDIT**: OK, I just saw your post at stackoverflow, will check your site.

**Comment by Rob75018** [comment]
Thanks a lot !
I could do a jsfiddle if you preffer, but you found my website...
My firefox is the latest on MacOs 10.7 (I just checked), and the videos on your website are ok. 
However they're relatively low definition, maybe could it be a reason ? 

My opinion is, that the non-support of mp4 vids in MacOs firefox has to be involved...
I'll carry on searching.

**Comment by picssel** [comment]
@Rob75018  I found this link http://www.reddit.com/r/webdev/comments/1v9xod/firefox_on_os_107_cannot_play_mp4_html5_video/ but not sure it can be related. Also, you may need to install an additional codec for your browser (depending how you are actually encoding your videos). BTW, notice [my comment](http://stackoverflow.com/questions/26649879/mediaelement-js-in-fancybox-choppy-video-on-firefox#comment41919413_26649879) at stackoverflow, your videos are asking to be downloaded instead of playing (at least in Firefox and Chrome Windows)

**Comment by Rob75018** [comment]
Found out what was going on and nothing related to your fancybox video...
That was about a slideshow in background causing frame gaps on animation.
My bad... 
Thanks for all !

**Comment by picssel** [comment]
@Rob75018 glad to hear it's solved. I guess we can close this issue then.
